{% set version = "0.3.0a1" %}
{% set js_version = version.replace("a", "-alpha.").replace("b", "-beta.").replace("rc", "-rc.") %}
{% set jupyterlab_version = ">=4.1.1,<4.2" %}

package:
  name: jupyterlite-core-split
  version: {{ version }}

source:
  - folder: jupyterlite-core
    url: https://pypi.io/packages/source/j/jupyterlite-core/jupyterlite_core-{{ version }}.tar.gz
    sha256: 6f193ffa2dd43ca9fb695ad71c2345d4696afba4b2e336f493e6df2dc48aa380

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
  run:
    - python >=3.8

outputs:
  - name: jupyterlite-core
    build:
      noarch: python
      script:
        - cd jupyterlite-core && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
        - {{ PYTHON }} {{ RECIPE_DIR }}/extract-third-party-licenses.py
      entry_points:
        - jupyter-lite = jupyterlite_core.app:main
    requirements:
      host:
        - hatchling >=1.6.3,<2
        - pip
        - python >=3.8
      run:
        - doit >=0.34,<1
        - importlib-metadata >=3.6
        - jupyter_core >=4.7
        - python >=3.8
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter-lite --help
      requires:
        - pip
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - jupyterlite-core/LICENSE
        - jupyterlite-core/third-party-licenses.json

  - name: jupyterlite-core-with-libarchive
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - {{ pin_subpackage("jupyterlite-core", max_pin="x.x.x") }}
        - python >=3.8
        - python-libarchive-c >=4.0
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter lite --help
      requires:
        - pip
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites (with libarchive)
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - jupyterlite-core/LICENSE

  - name: jupyterlite-core-with-lab
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - {{ pin_subpackage("jupyterlite-core", max_pin="x.x.x") }}
        - jupyterlab {{ jupyterlab_version }}
        - python >=3.8
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter lite --help
      requires:
        - pip
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites (with jupyterlab)
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - jupyterlite-core/LICENSE

  - name: jupyterlite-core-with-contents
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - {{ pin_subpackage("jupyterlite-core", max_pin="x.x.x") }}
        - jupyter_server
        - python >=3.8
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter lite --help
      requires:
        - pip
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites (with contents)
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - jupyterlite-core/LICENSE

  - name: jupyterlite-core-with-translation
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - {{ pin_subpackage("jupyterlite-core", max_pin="x.x.x") }}
        - jupyterlab_server >=2.8.1,<3
        - python >=3.8
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter lite --help
      requires:
        - pip
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites (with translation)
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - jupyterlite-core/LICENSE

  - name: jupyterlite-core-with-serve
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - {{ pin_subpackage("jupyterlite-core", max_pin="x.x.x") }}
        - tornado >=6.1
        - python >=3.8
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter lite --help
      requires:
        - pip
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites (with serve)
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - jupyterlite-core/LICENSE

  - name: jupyterlite-core-with-check
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - {{ pin_subpackage("jupyterlite-core", max_pin="x.x.x") }}
        - jsonschema-with-format-nongpl >=3
        - python >=3.8
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter lite --help
      requires:
        - pip
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites (with check)
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - jupyterlite-core/LICENSE

  - name: jupyterlite-core-with-all
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - {{ pin_subpackage("jupyterlite-core-with-check", max_pin="x.x.x") }}
        - {{ pin_subpackage("jupyterlite-core-with-contents", max_pin="x.x.x") }}
        - {{ pin_subpackage("jupyterlite-core-with-lab", max_pin="x.x.x") }}
        - {{ pin_subpackage("jupyterlite-core-with-libarchive", max_pin="x.x.x") }}
        - {{ pin_subpackage("jupyterlite-core-with-serve", max_pin="x.x.x") }}
        - {{ pin_subpackage("jupyterlite-core-with-translation", max_pin="x.x.x") }}
        - {{ pin_subpackage("jupyterlite-core", max_pin="x.x.x") }}
        - python >=3.8
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter lite --help
        - pytest -vv --pyargs jupyterlite_core --script-launch-mode=subprocess --cov=jupyterlite_core --cov-report=term-missing:skip-covered --cov-fail-under=82 --no-cov-on-fail
      requires:
        - diffoscope  # [linux]
        - pip
        - pytest-console-scripts >=1.4.0
        - pytest-cov
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites (with all)
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - jupyterlite-core/LICENSE

about:
  home: https://github.com/jupyterlite/jupyterlite
  summary: Tools for building JupyterLite sites
  doc_url: https://jupyterlite.readthedocs.io
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  feedstock-name: jupyterlite-core
  recipe-maintainers:
    - bollwyvl
    - jtpio
    - martinRenou
