{% set version = "0.3.0" %}
{% set js_version = version.replace("a", "-alpha.").replace("b", "-beta.").replace("rc", "-rc.") %}
{% set jupyterlab_version = ">=4.1.5,<4.2" %}
{% set min_python = "python >=3.8" %}

# handle undefined PYTHON in `noarch: generic` packages
{% if PYTHON is undefined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: jupyterlite-core-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlite-core/jupyterlite_core-{{ version }}.tar.gz
  sha256: 5a97e74a93d487c0a2ce6a4615cd721a39686cdce9d329c241404e985157f8f9

build:
  number: 0
  noarch: python

requirements:
  host:
    - {{ min_python }}
  run:
    - {{ min_python }}

outputs:
  - name: jupyterlite-core
    build:
      noarch: python
      script:
        - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
        - {{ PYTHON }} {{ RECIPE_DIR }}/extract-third-party-licenses.py
      entry_points:
        - jupyter-lite = jupyterlite_core.app:main
    requirements:
      host:
        - {{ min_python }}
        - hatchling >=1.6.3,<2
        - pip
      run:
        - {{ min_python }}
        - doit >=0.34,<1
        - importlib-metadata >=3.6
        - jupyter_core >=4.7
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter-lite --help
      requires:
        - pip
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - LICENSE
        - third-party-licenses.json

  - name: jupyterlite-core-with-libarchive
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("jupyterlite-core", max_pin="x.x.x") }}
        - python-libarchive-c >=4.0
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter lite --help
      requires:
        - pip
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites (with libarchive)
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - LICENSE

  - name: jupyterlite-core-with-lab
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("jupyterlite-core", max_pin="x.x.x") }}
        - jupyterlab {{ jupyterlab_version }}
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter lite --help
      requires:
        - pip
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites (with jupyterlab)
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - LICENSE

  - name: jupyterlite-core-with-contents
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("jupyterlite-core", max_pin="x.x.x") }}
        - jupyter_server
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter lite --help
      requires:
        - pip
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites (with contents)
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - LICENSE

  - name: jupyterlite-core-with-translation
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("jupyterlite-core", max_pin="x.x.x") }}
        - jupyterlab_server >=2.8.1,<3
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter lite --help
      requires:
        - pip
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites (with translation)
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - LICENSE

  - name: jupyterlite-core-with-serve
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("jupyterlite-core", max_pin="x.x.x") }}
        - tornado >=6.1
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter lite --help
      requires:
        - pip
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites (with serve)
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - LICENSE

  - name: jupyterlite-core-with-check
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("jupyterlite-core", max_pin="x.x.x") }}
        - jsonschema-with-format-nongpl >=3
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter lite --help
      requires:
        - pip
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites (with check)
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - LICENSE

  - name: jupyterlite-core-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("jupyterlite-core-with-check", max_pin="x.x.x") }}
        - {{ pin_subpackage("jupyterlite-core-with-contents", max_pin="x.x.x") }}
        - {{ pin_subpackage("jupyterlite-core-with-lab", max_pin="x.x.x") }}
        - {{ pin_subpackage("jupyterlite-core-with-libarchive", max_pin="x.x.x") }}
        - {{ pin_subpackage("jupyterlite-core-with-serve", max_pin="x.x.x") }}
        - {{ pin_subpackage("jupyterlite-core-with-translation", max_pin="x.x.x") }}
        - {{ pin_subpackage("jupyterlite-core", max_pin="x.x.x") }}
    test:
      imports:
        - jupyterlite_core
      commands:
        - pip check
        - jupyter lite --help
        - pytest -vv --pyargs jupyterlite_core --script-launch-mode=subprocess --cov=jupyterlite_core --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=93
      requires:
        - diffoscope  # [linux]
        - pip
        - pytest-console-scripts >=1.4.0
        - pytest-cov
    about:
      home: https://github.com/jupyterlite/jupyterlite
      summary: Tools for building JupyterLite sites (with all)
      doc_url: https://jupyterlite.readthedocs.io
      license: BSD-3-Clause
      license_file:
        - LICENSE

about:
  home: https://github.com/jupyterlite/jupyterlite
  summary: Tools for building JupyterLite sites
  doc_url: https://jupyterlite.readthedocs.io
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  feedstock-name: jupyterlite-core
  recipe-maintainers:
    - bollwyvl
    - jtpio
    - martinRenou
